### ISSUE TITLE
the number form accept 17 numbers even if it shows only 16

### ISSUE THREAD

**Issue by angelocapone** [ezet/stripe-sdk#9] opened 2019-11-07 15:02 UTC
VISA has 16 number (e.g. 4242424242424242)
The Number form accepts extra numbers even if it shows only 16.
here's the debugging:
I/flutter ( 3947): 4242 4242 4242 4242
I/flutter ( 3947): 4242 4242 4242 42429 

bool isValidCardNumber(String cardNumber) {

  print(cardNumber);

  String normalizedNumber = removeSpacesAndHyphens(cardNumber);

  print(normalizedNumber);
  
  return isValidLuhnNumber(normalizedNumber) &&
      isValidCardLength(normalizedNumber);
}

**Comment by angelocapone** [comment] 2019-11-07 15:15
I think this is related to masked_text_controller.dart

**Comment by ezet** [comment] 2019-11-07 20:27
This is probably the reason for #8 . I'll look into this when I have time :)

**Comment by ezet** [comment] 2019-11-07 20:30
I'm not able to reproduce this on demand tho. Do you have any steps to reproduce it ?

**Comment by angelocapone** [comment] 2019-11-08 05:33
To reproduce, I type more than 16 number in the Form field (even if it show only 16 on the screen).

**Comment by ezet** [comment] 2019-11-10 22:15
I'll fix this in the next release.

**Comment by ezet** [comment] 2019-11-18 22:12
Fixed in 707c200444d0307d9964db25db6dd83d8bf05445

**Closed** 2019-11-18 22:12 UTC
Labels: bug
