### ISSUE TITLE
Having an issue running on web (automaticpaymentintent) - need help/guidance

### ISSUE THREAD

**Issue by varunbhalerao56** [ezet/stripe-sdk#83] opened 2020-10-05 17:18 UTC
Hi sorry to bother you guys but I am using the stripe SDK on an app and it works perfectly fine for the android and iOS. I am able to make the payment update etc, but for web, the code isn't running as should be. Below is the error when i login from WEB

it would be really great i can get help for this as google really does not show any search for this. If anyone has an example for web that is also great  (checked out the sdk example already)

Failed to retrieve ephemeralKey from server
    at Object.throw_ [as throw] (http://localhost:60113/dart_sdk.js:4328:11)
    at ephemeral_key_manager.EphemeralKeyManager.new.retrieveEphemeralKey
    (http://localhost:60113/packages/stripe_sdk/src/ephemeral_key_manager.dart.lib.js:169:23)
    at retrieveEphemeralKey.throw (<anonymous>)
    at http://localhost:60113/dart_sdk.js:37599:38
    at _RootZone.runBinary (http://localhost:60113/dart_sdk.js:37452:58)
    at _FutureListener.thenAwait.handleError (http://localhost:60113/dart_sdk.js:32436:48)
    at handleError (http://localhost:60113/dart_sdk.js:32987:51)
    at Function._propagateToListeners (http://localhost:60113/dart_sdk.js:33013:17)
    at _Future.new.[_completeError] (http://localhost:60113/dart_sdk.js:32860:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60113/dart_sdk.js:32898:31)
    at Object._microtaskLoop (http://localhost:60113/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:60113/dart_sdk.js:37714:13)
    at http://localhost:60113/dart_sdk.js:33226:9

 when i try to buy an item
[log]NetworkService._call, createAutomaticPaymentIntent, {amount: 3700}
Error: FirebaseError: internal (internal)
    at Object.throw_ [as throw] (http://localhost:55340/dart_sdk.js:4463:11)
    at handleThenable (http://localhost:55340/packages/firebase/src/storage.dart.lib.js:3264:21)
    at handleThenable.throw (<anonymous>)
    at http://localhost:55340/dart_sdk.js:37181:38
    at _RootZone.runBinary (http://localhost:55340/dart_sdk.js:37034:58)
    at _FutureListener.thenAwait.handleError (http://localhost:55340/dart_sdk.js:32128:48)
    at handleError (http://localhost:55340/dart_sdk.js:32679:51)
    at Function._propagateToListeners (http://localhost:55340/dart_sdk.js:32705:17)
    at _Future.new.[_completeError] (http://localhost:55340/dart_sdk.js:32552:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55340/dart_sdk.js:32590:31)
    at Object._microtaskLoop (http://localhost:55340/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:55340/dart_sdk.js:37296:13)
    at http://localhost:55340/dart_sdk.js:32918:9

020-10-06 01:49:57.308269
GET /dart_sdk.js:4463:11
Error thrown by handler.
FormatException: Illegal scheme character (at character 5)
dart_sdk.js:4463:11
    ^

dart:core                                                     _Uri.resolve
package:flutter_tools/src/build_runner/devfs_web.dart 503:75  WebAssetServer._resolveDartFile
package:flutter_tools/src/build_runner/devfs_web.dart 331:17  WebAssetServer.handleRequest
package:dwds/src/handlers/injected_handler.dart 82:30         createInjectedHandler.<fn>.<fn>

**Comment by CiriousJoker** [comment] 2020-10-27 23:19
Duplicate of https://github.com/ezet/stripe-sdk/issues/87

**Closed** 2020-10-28 00:34 UTC
