### ISSUE TITLE
Card number validation issue with Test card

### ISSUE THREAD

**Issue by angelocapone** [ezet/stripe-sdk#8] opened 2019-11-06 08:13 UTC
I'm getting "Invalid number" when entering the Testing cards as per https://stripe.com/docs/testing
4242424242424242  VISA
5555555555554444  Mastercard

I'm using CardForm(card:card, formKey: formKey).

**Comment by ezet** [comment] 2019-11-18 22:15
Duplicate of #9

**Closed by ezet** 2019-11-18 22:15 UTC
